### ISSUE TITLE
bug: appversion unconsistency with rw version

### ISSUE THREAD

**Issue by yufansong** [risingwavelabs/helm-charts#23]
Report by some user, the actual rw version is not consistency with app version
![image](https://github.com/risingwavelabs/helm-charts/assets/33971064/c18a1bf8-a1f8-4f92-ae1b-da63faa411b0)
![image](https://github.com/risingwavelabs/helm-charts/assets/33971064/2602f152-1875-4b7b-9ac5-2fb5faa507db)

**Comment by arkbriar** [comment]
Let me validate it locally. BTW, [`appVersion`](https://helm.sh/docs/topics/charts/#the-appversion-field) isn't related to the [`version`](https://helm.sh/docs/topics/charts/#charts-and-versioning). I presume the version returned by the SQL query is wrong.

**Comment by arkbriar** [comment]
Nah, I didn't reproduce. I got the correct result from my local

```
 PostgreSQL 9.5-RisingWave-1.6.0 (71898b4873a32b9df911a8157864100c0dfab27d)
```

The helm chart doesn't restrict you from setting your own image version. That means one can deploy RisingWave v1.2.0 with the latest chart. I don't think this is a bug so I'm closing the issue.
