### ISSUE TITLE
Network slowness on aliyun when pulling container images

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/helm-charts#4]
> The pod is pulling container image abnormally because there are other pods pulling it at the same time, which may block the current process. The pods's container images are [ghcr.io/risingwavelabs/risingwave:v1.3.0 ghcr.io/risingwavelabs/risingwave:v1.3.0 ghcr.io/risingwavelabs/risingwave:v1.3.0].

> Pod my-risingwave-compactor-58d5c94d5b-jn99t 存在异常：拉取镜像超时

**Comment by arkbriar** [comment]
Just replaced the default registry with docker.io. Please try it with [the 0.1.28 version](https://github.com/risingwavelabs/helm-charts/releases/tag/risingwave-0.1.28).
