### ISSUE TITLE
Expose log level values

### ISSUE THREAD

**Issue by Babbleshack** [risingwavelabs/helm-charts#5]
RisingWave writes alot of logs. I would like to reduce `RUST_LOG` level for each service however these values are not exposed.

## TODO:

- [ ] Add `RUST_LOG` for each service to values.yaml

**Comment by arkbriar** [comment]
Hi @Babbleshack, thanks for the great advice. Just supported it in the version [0.1.29](https://github.com/risingwavelabs/helm-charts/releases/tag/risingwave-0.1.29).

Now you can set the `RUST_LOG` and `RUST_BACKTRACE` by setting the following values in each component:

```yaml
metaComponent:
  rustLog: INFO
  rustBacktrace: full
```

Check it out [here](https://github.com/risingwavelabs/helm-charts/blob/risingwave-0.1.29/charts/risingwave/values.yaml#L641-L649).
