### ISSUE TITLE
bug: The State Store use  Tencent's COS error

### ISSUE THREAD

**Issue by quinniup** [risingwavelabs/helm-charts#62]
## Describe the bug
- Use Tencent's COS, but meta, compute, compator node throw exception: 

<img width="787" alt="image" src="https://github.com/risingwavelabs/helm-charts/assets/28534155/dc5a4d4d-62b4-4cd7-bbdf-28cccab43be1">

## Error message/log
![image](https://github.com/risingwavelabs/helm-charts/assets/28534155/1f30136f-4077-4f1c-bc45-cb7095fbb4fa)

## How did you deploy RisingWave?
- master helm

## The version of RisingWave
No response

## Additional context
No response

**Comment by arkbriar** [comment]
According to the PR #63, this doesn't sound like a bug of the helm chart to me. It's more a implementation defect of COS.

**Comment by arkbriar** [comment]
Close since #62 is merged!
