### ISSUE TITLE
Support HPA settings for compute nodes

### ISSUE THREAD

**Issue by tcodehuber** [risingwavelabs/helm-charts#72]
I wonder wether we can enable HPA feature for compute nodes. From the official docs,  I could not find details about it.

**Comment by arkbriar** [comment]
Certainly. I also thought about it before but scaling of compute nodes requires additional human efforts to run several commands at that time. Now the auto-scaling is implemented, I think we can do it now. 

BTW, I would appreciate if you would like to contribute.

**Comment by arkbriar** [comment]
Supported in #75.
