### ISSUE TITLE
Value of `existingConfigMap` is ignored and static string `risingwave-configuration` is used instead to assign ConfigMap to PODs

### ISSUE THREAD

**Issue by Kyry** [risingwavelabs/helm-charts#78]
**Context**

There is helm value `existingConfigMap`, that is [annotated ](https://github.com/risingwavelabs/helm-charts/blob/main/charts/risingwave/values.yaml#L710) as
```
## @param existingConfigMap Name of existing ConfigMap containing RisingWave configuration.
## The ConfigMap must contain a key named `risingwave.toml`. If set, `configuration` will be ignored.
## 
```

**Expectation** 
I would therefore expect, that configmap, that is created (and whose name is then assigned to value of `existingConfigMap` ) would be used by RisingWave (and the .toml file included in CM will be used)

**Observation**

If `existingConfigMap` is not empty, then disregard of actual value, pod start to look for configmap with name `risingwave-configuration`

**Workaround**

Add custom .toml configuration into ConfigMap named `risingwave-configuration`

**Investigation**

In [configmap.yaml](https://github.com/risingwavelabs/helm-charts/blob/c51f4783fc79863a39ab290fc8b06b182b79ad56/charts/risingwave/templates/configmap.yaml), there is logic, that creates CM with name of  `risingwave.configurationConfigMapName`  in case `.Values.existingConfigMap` is not empty
```
{{- if empty .Values.existingConfigMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "risingwave.configurationConfigMapName" . }}
  labels:
      {{- include "risingwave.labels" . | nindent 4 }}
  {{- $annotations := (include "risingwave.annotations" . ) | trim }}
  {{- if $annotations }}
  annotations:
    {{ nindent 4 $annotations }}
  {{- end }}
data:
  risingwave.toml: |
    {{ .Values.configuration | nindent 4 }}
{{- end }}
```

In other files (e.g. [compactor-deploy.yaml](https://github.com/risingwavelabs/helm-charts/blob/c51f4783fc79863a39ab290fc8b06b182b79ad56/charts/risingwave/templates/compactor-deploy.yaml)) only value of `configurationConfigMapName` is used (ignoring `.Values.existingConfigMap`)

**Comment by arkbriar** [comment]
Thanks! This is a real bug! Good catch!
